
package ws.unit04.example1.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DividedByZeroException", targetNamespace = "http://webservices.ejemplo1.ws/")
public class DividedByZeroException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DividedByZeroException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DividedByZeroException_Exception(String message, DividedByZeroException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DividedByZeroException_Exception(String message, DividedByZeroException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.unit04.example1.webservice.DividedByZeroException
     */
    public DividedByZeroException getFaultInfo() {
        return faultInfo;
    }

}
