
package ws.unit04.example1.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICalculator", targetNamespace = "http://webservices.ejemplo1.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICalculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservices.ejemplo1.ws/", className = "ws.unit04.example1.webservice.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservices.ejemplo1.ws/", className = "ws.unit04.example1.webservice.AddResponse")
    @Action(input = "http://webservices.ejemplo1.ws/ICalculator/addRequest", output = "http://webservices.ejemplo1.ws/ICalculator/addResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     * @throws DividedByZeroException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://webservices.ejemplo1.ws/", className = "ws.unit04.example1.webservice.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://webservices.ejemplo1.ws/", className = "ws.unit04.example1.webservice.DivResponse")
    @Action(input = "http://webservices.ejemplo1.ws/ICalculator/divRequest", output = "http://webservices.ejemplo1.ws/ICalculator/divResponse", fault = {
        @FaultAction(className = DividedByZeroException_Exception.class, value = "http://webservices.ejemplo1.ws/ICalculator/div/Fault/DividedByZeroException")
    })
    public double div(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws DividedByZeroException_Exception
    ;

}
